#!/bin/sh
# $Id$
#
# Distributed under the GPL
#
# watchdog script to restart vdr after failure
# to stop watchdog temporarily touch /tmp/nowatchdog
#
#

#detach from terminal
LOGFILE=${1:-/dev/null}
exec < /dev/null
exec >>${LOGFILE} 2>&1


signal_stopped=0

sig_hup()
{
	periodic_function
}

trap sig_hup SIGHUP

periodic_function() {
	[ -f /tmp/no-vdr-watchdog ] && return

	[ "$signal_stopped" = "1" ] && return

	if ! pidof /usr/bin/vdr > /dev/null; then
		logger -i -t vdrwatchdog -p local0.info "initializing full VDR restart"
		date
		/etc/init.d/vdr watchdogrestart
		/usr/bin/svdrpsend.pl mesg "Warning: vdr was restarted by watchdog."
	fi
}

echo started watchdog
while sleep 8; do
	periodic_function
done
echo ended watchdog
